force-app/main/default/objects/Salesforce_DevOps_Task__c/Salesforce_DevOps_Task__c.object-meta.xml
<CustomObject>
    <label>Salesforce DevOps Task</label>
    <nameField>
        <label>Task</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce DevOps Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_DevOps_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <label>Assigned To</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Jack</fullName>
            </value>
            <value>
                <fullName>Sonny</fullName>
            </value>
            <value>
                <fullName>Tito</fullName>
            </value>
            <value>
                <fullName>Zac</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_DevOps_Task__c/fields/Importance__c.field-meta.xml
<CustomField>
    <fullName>Importance__c</fullName>
    <label>Importance</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_DevOps_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DevopsDashboardController.cls
public without sharing class DevopsDashboardController {
	@AuraEnabled(Cacheable=true)
	public static List<Salesforce_DevOps_Task__c> getAllTasks(String random) {
		return [
			SELECT id, name, assigned_to__c, status__c, importance__c
			FROM Salesforce_DevOps_Task__c
			WHERE status__c != 'Completed'
		];
	}
	@AuraEnabled(Cacheable=true)
	public static List<String> getPeople() {
		List<string> picklistvalues = new List<string>();
		for (
			Schema.PicklistEntry pickListVal : Salesforce_DevOps_Task__c.assigned_to__c.getDescribe()
				.getPicklistValues()
		) {
			picklistvalues.add(pickListVal.getLabel());
		}
		return picklistvalues;
	}
}